backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;

use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\User;
use common\models\LoginForm;
use common\models\UserSearch;
use common\models\MenuSchedulesSearch;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index','schedules','viewschedule'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login(3)) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
	public function actionSchedules(){
		$searchModel = new UserSearch();
		$searchModel->is_supplier = 'yes';
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		return $this->render('schedules',[
			'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
		]);
	}
	public function actionViewschedule($id){
		
		$user_info	= User::findOne($id);
		if(empty($user_info))
			throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
		if($user_info->is_supplier!='yes')
			throw new ForbiddenHttpException('You\'re not authorized to view this page.');
		
		$searchModel = new MenuSchedulesSearch();
		$searchModel->supplier_id = $id;
        $dataProvider = $searchModel->searchSch(Yii::$app->request->queryParams);
		
		return $this->render('viewschedule',['user_info'=>$user_info,'dataProvider'=>$dataProvider,'searchModel'=>$searchModel]);
	}
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\Order;
use common\models\UserFavMenu;
use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\data\ActiveDataProvider;
use yii\db\Expression;
use frontend\components\AuthHandler;
use common\models\{Pages,
    User,
    SortMethod,
    Menu,
    Library,
    UserAddress,
    UserRole,
    MainCategories,
    Subscriptions,
    LoginForm,
    Apiuser,
    Brand,
    Category,
    Braintree};
use common\models\HelpRequests;
use common\models\Countries;
use common\models\UserFavSupplier;
use common\models\MenuToAttributes;
use common\models\SubscriptionTransaction;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\models\Search;
use api\models\Cart;
use Faker;
use yii\web\NotFoundHttpException;
use yii\helpers\Html;
/**
 * Site controller
 */
class SiteController extends Controller
{
    public $screen_id;
    public $page_size=12;
    public $statusCode = 200;
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['add-to-fav-supp','logout', 'add-to-fav', 'add-to-cart','switch-to-supplier','switch-to-buy'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'checknumber' => ['post'],
                    'subscribe' => ['post'],
                    'logout' => ['post'],
                    'add-to-fav' => ['post'],
                    'add-to-fav-supp' => ['post'],
                    'add-to-cart' => ['post'],
                    'guest-add-to-cart' => ['post'],
                    'search-items' => ['GET'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'onAuthSuccess'],
            ],
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
    public function beforeAction($action) {
        if($action->id == 'btree-webhook') {
            Yii::$app->request->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
    }
    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {

        $lang = $_GET['lang'] ?? 0;
        $country = $_GET['country'] ?? 0;
        $session = Yii::$app->session;
        if(isset($_GET['UserAddress']['is_default']) && !yii::$app->user->isGuest){
            $user_id = Yii::$app->user->id;
            $address_id = $_GET['UserAddress']['is_default'];
            $model		= new UserAddress();
            $result = $model->find()->where(['user_id'=> $user_id,'address_id'=>$address_id,'is_delete'=>0])->one();
            if(!empty($result)){
                UserAddress::updateAll(['is_default'=>'no'],'user_id='.$user_id);
                $result->is_default = 'yes';
                $result->save();
                return $this->goBack();
            }
        }
        if(!empty($lang)){
            $lang_id  = 1;
            if($lang=='ar')
                $lang_id  = 2;
            $session->set('language_id', $lang_id);
            return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);

        }
        if(!empty($country)){
            $country_data = Countries::find()->where(['iso_code_2' => $country,'status' => 1])->asArray()->one();
            $session->set('country_name', $country_data['name']);
            return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);
        }
        if(isset($_REQUEST['menu_type'])){
            $menu_category = new MainCategories();
            $menu_category = $menu_category->find()->where(['status' => 1,'code' => $_REQUEST['menu_type']])->asArray()->one();
            if(!empty($menu_category)){
                $session = Yii::$app->session;
                $session->set('screen_id', $menu_category['id']);
                return $this->redirect(Yii::$app->request->baseUrl.'/products');
                //return $this->goBack((!empty(Yii::$app->request->referrer) ? Yii::$app->request->referrer : null));
            }
        }
        if(isset($_REQUEST['u'])){
            $user_info = User::findByUsername($_REQUEST['u']);

            if(!empty($user_info)){
                $cookies = Yii::$app->response->cookies;
                $cookies->readOnly = false;
                $cookies->add(new \yii\web\Cookie([
                    'name' => 'refer_by',
                    'value' => $user_info->id,
                    'expire' => time()+2592000,
                ]));

            }
        }

        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        $session = Yii::$app->session;
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new LoginForm();
        $request = Yii::$app->request;
        if ($request->isAjax) {
            $json = [];
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            if ($model->load(Yii::$app->request->post()) && $model->login(null)) {
                if($session->has('guest_cart')){
                    $user_info = Yii::$app->user->identity;
                    $user_info->cart = $session->get('guest_cart');
                    $user_info->save();
                }
                $json['success'] = true;
            }else{
                $all_errors	= [];
                $errors	= $model->getErrors();
                foreach($errors as $key=>$error){
                    $all_errors[]	= $error[0];
                }
                $json['error']	= !empty($all_errors) ? $all_errors[0] : '' ;

            }
            return $json;
        }else{

            if ($model->load(Yii::$app->request->post()) && $model->login(null)) {

                $session->set('is_supplier', true);
                return $this->goBack();
            } else {
                $model->password = '';

                return $this->render('login', [
                    'model' => $model,
                ]);
            }
        }

    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContactUs()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(config_email)) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {

        $model = new SignupForm();
        $model->scenario = 'registration';
        $model->role = 1;
        $request = Yii::$app->request;
        if ($request->isAjax) {
            $json = [];
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            if ($model->load(Yii::$app->request->post()) && $model->signup()) {
                Yii::$app->session->setFlash('success', 'Thank you for registration. Please check your inbox for verification email.');
                $json['success'] = true;
            }else{
                $all_errors	= [];
                $errors	= $model->getErrors();
                foreach($errors as $key=>$error){
                    $all_errors[]	= $error[0];
                }
                $json['error']	= !empty($all_errors) ? $all_errors[0] : '' ;
            }
            return $json;
        }else{
            $model = new User();
            $model->scenario = 'checknumber';

            if (isset($_POST['signup-button-1']) && $model->load(Yii::$app->request->post()) && $model->validate()) {
                $phone_number = $model->phone_number;

                $model = new User();
                $model->scenario = 'checknumber1';

                $model->phone_number = $phone_number;

                return $this->render('signup/_step2',['model' => $model]);
            }elseif(isset($_POST['g-recaptcha-response'])){
                $phone_number = '';
                if(isset($_POST['User']['phone_number']))

backend/views/site/_treePart2.php
<?php
$node->cat_id = $cat_id;
echo $form->field($node, 'cat_id')->hiddenInput()->label(false);

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = config_name;
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Welcome to <?= config_name ?>!</h1>
    </div>

    
</div>

backend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/site/schedules.php
<?php
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\grid\GridView;
use yii\widgets\Pjax;
use kartik\select2\Select2;
use common\models\City;

$this->title = 'Schedules';
$this->params['breadcrumbs'][] = $this->title;

$all_cities = ArrayHelper::map(City::find()->where(['status'=>'active'])->all(), 'id', 'city_name');
?>

<div class="schedules-index">
	<h3>All <?= Html::encode($this->title) ?></h3>
	<?php Pjax::begin(); ?>
<div class="table-responsive">	
	<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
			'share_id',
			'name',
            'email:email',
			[
				'attribute'=>'status',
				'filter'=>Select2::widget([
                    'model' => $searchModel,
                    'attribute' => 'status',
                    'data' => [10=>'Active',0=>'In active'],
                    'options' => [
                        'placeholder' => 'Please select ...',
                    ],
					'pluginOptions' => [
                        'allowClear' => true
                    ],
                    
                ]),
				'value'=>function($data){
					return $data->status === 10 ? 'Active' : 'In active';
				}
			],
            [
				'attribute'=>'city',
				'filter'=>Select2::widget([
                    'model' => $searchModel,
                    'attribute' => 'city',
                    'data' => $all_cities,
                    'options' => [
                        'placeholder' => 'Please select ...',
                    ],
					'pluginOptions' => [
                        'allowClear' => true
                    ],
                    
                ]),
				'value'=>function($data){
					return !empty($data->city) ? $data->cityInfo->city_name : null;
				}
			],
            [
				'class' => 'yii\grid\FaActionColumn',
				'template'=>'{schedule}',
				'buttons'=>[
					'schedule'=>function($url, $model, $key){
						return Html::a(Html::tag('i','',['class'=>'fas fa-calendar-alt']), ['site/viewschedule','id' => $model->id], ['data-pjax' => 0,'title'=>'View schedule','class'=>'btn btn-primary']);
					}
				]
				
			],
        ],
        'pager' => [
            'pageCssClass' => 'page-item',
            'disabledPageCssClass' => 'page-link disabled',
            'prevPageLabel' => '<i class="fa fa-angle-double-left"></i>',
            'nextPageLabel' => '<i class="fa fa-angle-double-right"></i>',
            'linkOptions' => ['class' => 'page-link'],
        ]
    ]); ?>
</div>	
	<?php Pjax::end(); ?>
</div>

backend/views/site/viewschedule.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'All Suppliers'), 'url' => ['/user/supplier']];
$this->title = $user_info->name.'\'s Schedules';
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="viewschedule-index table-responsive">
	<?php Pjax::begin(); ?>
	<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
			'schedule_date',
			'start_time',
            'end_time',
            'choices',
			[
				'attribute'=>'supplier_id',
				'filter'=>false,
				'header'=>'items',
				'format'=>'raw',
				'value'=>function($data){
					return $data->menuitems;
				}
			],
            
        ],
    ]); ?>
	<?php Pjax::end(); ?>
</div>