common/models/Brand.php
<?php

namespace backend\models;
use Yii;


namespace common\models;
use himiklab\thumbnail\EasyThumbnailImage;
use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "brand".
 *
 * @property int $brand_id
 * @property string $name   
 * @property string $image
 */
class Brand extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */

     public function behaviors() 
    { 
        return [
            TimestampBehavior::className(),
        ];
    }

     public $brand_names;
     public $maincategoryid;
     

    public static function tableName()
    {
        return '{{%brand}}'; 
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['brand_names'], 'required'],
            // [['brand_id'], 'integer'],
            // [['name'], 'string', 'max' => 55],
            [['image'], 'string', 'max' => 250],
            // [['brand_id'], 'unique'],
            [['created_at', 'updated_at'], 'integer'],

        ]; 
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            // 'brand_id' => 'Brand ID',
            'name' => 'Name',
            'image' => 'Image',
            'brand_id' => 'Brand',
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    public function getBrandDescription()
    {
        return $this->hasOne(BrandDescription::className(), ['brand_id' => 'brand_id']);
    }
    public function getBrandCategories()
    {
        return $this->hasMany(BrandCategory::className(), ['brand_id' => 'brand_id']);
    }

    public function getBrandImage($sizeX=100,$sizeY=100){
        if(empty($this->image))
            $this->image = 'no_image.png';
        $image          = '../../frontend/web/uploads/'.$this->image;
        $p_image    = EasyThumbnailImage::thumbnailFileUrl(
            $image,$sizeX,$sizeY,EasyThumbnailImage::THUMBNAIL_INSET
        );
        return $p_image;
    }
}

common/models/Category.php
<?php

namespace common\models;

use himiklab\thumbnail\EasyThumbnailImage;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\BlameableBehavior;
use yii\helpers\Url;

/**
 * This is the model class for table "{{%category}}".
 *
 * @property int $category_id
 * @property int $parent_id
 * @property int $cat_id
 * @property string $name
 * @property string $image
 * @property int $active
 * @property int $created_by
 * @property int $created_at
 * @property int $updated_at
 * @property int $sort_order
 *
 * @property AttributeGroupCategory[] $attributeGroupCategories
 * @property User $createdBy
 * @property MainCategory $cat
 * @property Category $parent
 * @property Category[] $categories
 * @property MenuCategory[] $menuCategories
 */
class Category extends \yii\db\ActiveRecord
{
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            BlameableBehavior::className(),
        ];
    }
   
     public $name;
     public $name1;
     public $image1;
     public $active1;
    
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%category}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['home_category_id','parent_id', 'cat_id', 'active','active1', 'created_by','sort_order', 'created_at', 'updated_at'], 'integer'],
            [['home_category_id','cat_id','slug'], 'required'],
            [['cat_id'], 'trim'], 
            [['name'], 'required'],
            [['image','image1'], 'string', 'max' => 255],
            [['created_by','image1'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['cat_id'], 'exist', 'skipOnError' => true, 'targetClass' => MainCategories::className(), 'targetAttribute' => ['cat_id' => 'id']],
            [['parent_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['parent_id' => 'category_id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'category_id' => Yii::t('app', 'Category ID'),
            'parent_id' => Yii::t('app', 'Parent Category'),
            'cat_id' => Yii::t('app', 'Cat ID'),
            // 'name' => Yii::t('app', 'Name'),
            'home_category_id' => Yii::t('app', 'Home Category'), 
              
            'active' => Yii::t('app', 'Status'),
            'created_by' => Yii::t('app', 'Created By'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAttributeGroupCategories()
    {
        return $this->hasMany(AttributeGroupCategory::className(), ['category_id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCat()
    {
        return $this->hasOne(MainCategory::className(), ['id' => 'cat_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getParent()
    {
        return $this->hasOne(Category::className(), ['category_id' => 'parent_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategories()
    {
        return $this->hasMany(Category::className(), ['parent_id' => 'category_id']);
    }

    public function getParentCategory()
    {
        return $this->hasMany(Category::className(), ['parent_id' => 'category_id'])->joinWith('categoryDescription as cd')->where(['and',['active' => 1],['cd.language_id' => language_id]]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMenuCategories()
    {
        return $this->hasMany(MainCategories::className(), ['category_id' => 'category_id']);
    }

    public function saveCategoryPath(){
        // MySQL Hierarchical Data Closure Table Pattern
        $level = 0;
        $results = CategoryPath::find()->where(['category_id' => $this->parent_id])->orderBy("level ASC")->all();
        if(!empty($results)){
            foreach ($results as $result){
                $model = new CategoryPath();
                $model->category_id = $this->category_id;
                $model->path_id = $result->path_id;
                $model->level = $level;
                $model->save();
                $level++;
            }
        }
        $model = new CategoryPath();
        $model->category_id = $this->category_id;
        $model->path_id = $this->category_id;
        $model->level = $level;
        $model->save();
    }

    public function updateCategoryPath(){
        // MySQL Hierarchical Data Closure Table Pattern
        $results = CategoryPath::find()->where(['path_id' => $this->category_id])->orderBy("level ASC")->all();
        if(!empty($results)){
            foreach ($results as $result) {
                // Delete the path below the current one
                CategoryPath::deleteAll(['and',['category_id' => $result->category_id],['<','level',$result->level]]);
                $path = [];

                // Get the nodes new parents
                $category_paths = CategoryPath::find()->where(['category_id' => $this->parent_id])->orderBy("level ASC")->all();
                if(!empty($category_paths)){
                    foreach ($category_paths as $category_path)
                        $path[] = $category_path->path_id;
                }

                // Get whats left of the nodes current path
                $category_paths = CategoryPath::find()->where(['category_id' => $result->category_id])->orderBy("level ASC")->all();
                if(!empty($category_paths)){
                    foreach ($category_paths as $category_path)
                        $path[] = $category_path->path_id;
                }

                // Combine the paths with a new level
                $level = 0;
                foreach ($path as $path_id) {
                    $model = CategoryPath::find()->where(['path_id' => $path_id,'category_id' => $result->category_id])->one();
                    if(!$model) $model = new CategoryPath;
                    $model->category_id = $result->category_id;
                    $model->path_id = $path_id;
                    $model->level = $level;
                    $model->save();
                    $level++;
                }
            }
        }else{
            // Delete the path below the current one
            CategoryPath::deleteAll(['category_id' => $this->category_id]);

            // Fix for records with no paths
            $level = 0;

            $results = CategoryPath::find()->where(['category_id' => $this->parent_id])->orderBy("level ASC")->all();
            if(!empty($results)){
                foreach ($results as $result){
                    $model = new CategoryPath();
                    $model->category_id = $this->category_id;
                    $model->path_id = $result->path_id;
                    $model->level = $level;
                    $model->save();
                    $level++;
                }
            }

            $model = CategoryPath::find()->where(['category_id' => $this->category_id])->one();
            if(!$model) $model = new CategoryPath;
            $model->category_id = $this->category_id;
            $model->path_id = $this->category_id;
            $model->level = $level;
            $model->save();
        }
    }

    static public function getAllCategories($cat_id,$condition=[]){
        $query =  CategoryPath::find()
            ->select('cp.category_id AS category_id, GROUP_CONCAT(c2.name ORDER BY cp.level SEPARATOR \'&nbsp;&nbsp;&gt;&nbsp;&nbsp;\') AS name')
            ->alias('cp')
            ->leftJoin('tbl_category as c1 ON (cp.category_id = c1.category_id)')
            ->leftJoin('tbl_category as c2 ON (cp.path_id = c2.category_id)')
            ->where(['in','c1.cat_id', $cat_id]);
        if(!empty($condition))
            $query->andWhere($condition);

        $query->groupBy('cp.category_id')->orderBy('c1.name');
        $result = $query->asArray()->all();
        return $result;
    }
    static public function getCategoryName($category_id){
        return CategoryPath::find()
            ->select('cp.category_id AS category_id, GROUP_CONCAT(c2.name ORDER BY cp.level SEPARATOR \'&nbsp;&nbsp;&gt;&nbsp;&nbsp;\') AS name')
            ->alias('cp')
            ->leftJoin('tbl_category as c1 ON (cp.category_id = c1.category_id)')
            ->leftJoin('tbl_category as c2 ON (cp.path_id = c2.category_id)')
            ->where(['c1.category_id' => $category_id])

            ->asArray()
            ->one();
    }

    public function getCategoryImage(){
        if(!empty($this->image))
            return Yii::$app->params['website_path'].'/uploads/'.$this->image;
    }

    public function getCategoryDescription()
    {
        return $this->hasOne(CategoryDescription::className(), ['category_id' => 'category_id']);
    }

    public function getCategoryUrl(){
        if(!empty($this->slug))
            return Url::to(Yii::$app->request->baseUrl.'/category/'.$this->slug,true);
        return Url::to(Yii::$app->request->baseUrl.'/category?category_id='.$this->category_id,true);
    }

    public function getParentCategories($category_id){
        $category = Category::findOne($category_id);

        if(empty($category))
            return $categories ?? [];
        if(!empty($category)){
            $categories[] = $category->category_id;
            if(!empty($category->parent_id)){
                $child_items =  $this->getParentCategories($category->parent_id);
                if(!empty($child_items))

frontend/controllers/CategoryController.php
<?php

namespace frontend\controllers;
use common\models\Brand;
use common\models\Menu;
use Yii;
use common\models\Category;
use common\models\BrandCategory;
use common\models\MenuCategories;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\data\ActiveDataProvider;
/**
 * Category controller
 */
class CategoryController extends Controller
{
    public $page_size=12;
    public function actionIndex($slug=null,$category_id=null){
        $category =  Category::find();
        $query = $category->select('*')->joinWith('categoryDescription as cd')->where(['active' => 1,'cd.language_id' => language_id]);
        if(!empty($slug))
            $query->andWhere(['tbl_category.slug' => $slug]);
        elseif(!empty($category_id))
            $query->andWhere(['tbl_category.category_id' => $category_id]);
        else
            $query->andWhere(['category_id' => 0]);
        $result = $query->one();
        if(!$result)
            throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));


        $query = Category::find()->joinWith('categoryDescription as cd')->where(['and',['active' => 1],['parent_id' => $result->category_id],['cd.language_id' => language_id]]);
        $dataProvider	=  new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'defaultPageSize' => $this->page_size,
            ],
        ]);

        $query = BrandCategory::find()->joinWith(['brand','brand.brandDescription as bd'])->where(['in','category_id',$result->category_id])->andWhere(['bd.language_id' => language_id]);
        $brandDataProvider	=  new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'defaultPageSize' => $this->page_size,
            ],
        ]);

        $query = MenuCategories::find()->joinWith('menu as menu')->where(['in','category_id', $result->category_id])->groupBy('menu.supplier_id');
        $supplierDataProvider	=  new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'defaultPageSize' => $this->page_size,
            ],
        ]);


        return $this->render('index',['result' => $result,'dataProvider' => $dataProvider,'brandDataProvider' => $brandDataProvider,'supplierDataProvider' => $supplierDataProvider]);
    }

    public function actionBrand($brand_id){
        $sort_order = ['id' => SORT_DESC];
        $result = Brand::find()->joinWith('brandDescription as bd')->where(['tbl_brand.brand_id' => $brand_id,'bd.language_id' => language_id,'tbl_brand.status' => 1])->one();
        if(!empty($result)){
            $query = Menu::find()->joinWith('supplierInfo')->where(['and',['tbl_menu.image_approval'=>1,'tbl_menu.is_delete'=>0,'tbl_menu.test_data'=>0,'tbl_menu.brand_id'=>$brand_id],['>','subscription_end',time()]]);
            if (!Yii::$app->user->isGuest)
                $query->andWhere(['!=','supplier_id',Yii::$app->user->identity->id]);
            $dataProvider	=  new ActiveDataProvider([
                'query' => $query,
                'pagination' => [
                    'defaultPageSize' => $this->page_size,
                ],
                'sort' => [
                    'defaultOrder' => $sort_order
                ],
            ]);

            return $this->render('brand',['result' => $result,'dataProvider' => $dataProvider]);
        }else
            throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }

}

frontend/views/category/_brand.php
<div class="col-md-3 col-6 mb-3">
    <div class="brandlisting mb-3">
        <a href="<?= Yii::$app->request->baseUrl.'/brand?brand_id='.$model->brand_id ?>">
            <img src="<?= $model->brand->getBrandImage(251,200) ?>" class="img-fluid">
            <div class="category-name">
                <h5><?= $model->brand->brandDescription->brand_name ?></h5>
            </div>
        </a>
    </div>
</div>

frontend/views/category/_category.php
<div class="col-md-3 col-6">
    <a href="<?= $model->categoryUrl ?>">
    <div class="categorylisting mb-3">
        <img src="<?= $model->getProductImage(251,200) ?>" class="img-fluid">
        <div class="category-name">
            <h5><?= $model->categoryDescription->category_name ?></h5>
        </div>
    </div>
    </a>
</div>

frontend/views/category/_supplier.php
<?php
$supplier_info = $model->menu->supplierInfo;

?>
<div class="col-md-2 col-6">
    <a href="<?= $supplier_info->profileUrl ?>">
    <div class="supplierlisting mb-3">
        <img src="<?= $supplier_info->getSuppImage(251,200) ?>" class="img-fluid">
        <h5><?= $supplier_info->name ?></h5>
    </div>
    </a>
</div>

frontend/views/category/brand.php
<?php
use yii\widgets\Pjax;
use yii\widgets\ListView;
$this->title = $result->brandDescription->brand_name;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="bg-sec">
    <div class="container">
        <div class="heading">
            <h3><?= $this->title ?></h3>
            <div class="divider"></div>
        </div>
    </div>
</div>
<section class="product">
    <div class="container">
        <?php Pjax::begin(); ?>
        <?=  ListView::widget([
            'layout' => "<div class='col-sm-12'>{summary}</div>\n {items}\n<div class='col-sm-12 mt-3'><div class='pagination-sec'><nav aria-label='Page navigation example'>{pager}</nav></div>",
            'dataProvider' => $dataProvider,
            'itemView' => '//products/_view_product',
            'options' => [
                'tag' => 'div',
                'class' => 'row',
                'id' => 'list-wrapper',
            ],
            'itemOptions' => [
                'tag' => false
            ],
            'pager' => [
                'options' => ['class'=>'pagination justify-content-end'],
                'prevPageLabel' =>'Previous',
                'nextPageLabel' =>'Next',
                'pageCssClass' => 'page-item',
                'disabledPageCssClass' => 'page-link disabled',
                'linkOptions' => ['class' => 'page-link'],
            ]
        ]); ?>
        <?php Pjax::end(); ?>
    </div>
</section>

frontend/views/category/index.php
<?php
use yii\widgets\ListView;
use common\models\Category;
use common\models\HomeCategory;

$this->title = $result->categoryDescription->category_name;
$home_categories = HomeCategory::find()->select('*')->joinWith('homeCategoryDescription as hd')->where(['status' => 1,'hd.language_id' => language_id])->andWhere(['not IN','tbl_home_category.home_category_id',[29,30]])->asArray()->all();
?>
<section class="product-filter-section categorypage pb-5">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 mt-3">
                <div class="product-filter mt-3">
                    <p class="mb-1"><?= Yii::t('app','Filter By') ?>:</p>
                    <?php
                        if(!empty($home_categories)):
                            foreach ($home_categories as $home_category):
                                $categories = Category::find()->select('*')->joinWith('categoryDescription as cd')->where(['and',['home_category_id' => $home_category['home_category_id']],['IS','parent_id',NULL],['active' => 1],['cd.language_id' => language_id]])->all();
                    ?>
                        <h5><?= $home_category['home_category_name'] ?></h5>
                            <?php if(!empty($categories)): ?>
                                <ul class="cat-filter">
                                    <?php foreach ($categories as $category): ?>
                                        <li><a href="<?= $category->categoryUrl ?>"><?= $category->categoryDescription->category_name ?></a></li>
                                    <?php endforeach; ?>
                                </ul>
                            <?php endif;
                    endforeach;
                        endif;
                    ?>

                </div>
            </div>
            <div class="col-md-10">
                <div class="productlist categorylist mt-4">
                    <div class="row">
                        <div class="col-md-12">
                            <h5 class="mt-1"><?= $result->categoryDescription->category_name; ?></h5>
                        </div>
                        <div class="col-md-6 col-8">
                            <p><?= Yii::t('app','Shop By Category') ?></p>
                        </div>
                        <div class="col-md-6 col-4">

                        </div>
                    </div>
                </div>
                <div class="latest-products best-selling-product allproductlisting mt-3">
                    <?=  ListView::widget([
                        'layout' => "<div class='col-sm-12'>{summary}</div>\n {items}\n<div class='col-sm-12 mt-3'><div class='pagination-sec'><nav aria-label='Page navigation example'>{pager}</nav></div>",
                        'summary' => false,
                        'itemView' => '_category',
                        'dataProvider' => $dataProvider,
                        'options' => [
                            'tag' => 'div',
                            'class' => 'row',
                            'id' => '_category',
                        ],
                        'itemOptions' => [
                            'tag' => false
                        ],
                        'pager' => [
                            'options' => ['class'=>'pagination justify-content-center'],
                            'prevPageLabel' =>'<i class="fas fa-angle-double-left"></i>',
                            'nextPageLabel' =>'<i class="fas fa-angle-double-right"></i>',
                            'pageCssClass' => 'page-item',
                            'disabledPageCssClass' => 'page-link disabled',
                            'linkOptions' => ['class' => 'page-link'],
                        ]
                    ]); ?>
                </div>

                <div class="productlist categorylist mt-2">
                    <div class="row">
                        <div class="col-md-6 col-8">
                            <p><?= Yii::t('app','Shop By Supplier') ?></p>
                        </div>
                        <div class="col-md-6 col-4">
                            <p class="text-right"></p>
                        </div>
                    </div>
                </div>
                <div class="latest-products best-selling-product allproductlisting mt-3">
                    <?=  ListView::widget([
                        'layout' => "<div class='col-sm-12'>{summary}</div>\n {items}\n<div class='col-sm-12 mt-3'><div class='pagination-sec'><nav aria-label='Page navigation example'>{pager}</nav></div>",
                        'summary' => false,
                        'itemView' => '_supplier',
                        'dataProvider' => $supplierDataProvider,
                        'options' => [
                            'tag' => 'div',
                            'class' => 'row',
                            'id' => '_category',
                        ],
                        'itemOptions' => [
                            'tag' => false
                        ],
                        'pager' => [
                            'options' => ['class'=>'pagination justify-content-center'],
                            'prevPageLabel' =>'<i class="fas fa-angle-double-left"></i>',
                            'nextPageLabel' =>'<i class="fas fa-angle-double-right"></i>',
                            'pageCssClass' => 'page-item',
                            'disabledPageCssClass' => 'page-link disabled',
                            'linkOptions' => ['class' => 'page-link'],
                        ]
                    ]); ?>
                </div>

                <div class="productlist categorylist mt-2">
                    <div class="row">
                        <div class="col-md-6 col-8">
                            <p><?= Yii::t('app','Shop By Brands') ?></p>
                        </div>
                        <div class="col-md-6 col-4">
                            <p class="text-right"></p>
                        </div>
                    </div>
                </div>
                <div class="latest-products best-selling-product allproductlisting mt-3">
                    <?=  ListView::widget([
                        'layout' => "<div class='col-sm-12'>{summary}</div>\n {items}\n<div class='col-sm-12 mt-3'><div class='pagination-sec'><nav aria-label='Page navigation example'>{pager}</nav></div>",
                        'summary' => false,
                        'itemView' => '_brand',
                        'dataProvider' => $brandDataProvider,
                        'options' => [
                            'tag' => 'div',
                            'class' => 'row',
                            'id' => '_category',
                        ],
                        'itemOptions' => [
                            'tag' => false
                        ],
                        'pager' => [
                            'options' => ['class'=>'pagination justify-content-center'],
                            'prevPageLabel' =>'<i class="fas fa-angle-double-left"></i>',
                            'nextPageLabel' =>'<i class="fas fa-angle-double-right"></i>',
                            'pageCssClass' => 'page-item',
                            'disabledPageCssClass' => 'page-link disabled',
                            'linkOptions' => ['class' => 'page-link'],
                        ]
                    ]); ?>
                </div>
            </div>
        </div>
    </div>
</section>